#!/usr/bin/env python

import sys
import smtplib
from email.mime.text import MIMEText


if __name__ == "__main__":

    sender = sys.argv[1]
    receivers = [sender]
    msg = MIMEText( "Balrog job %s finished. \n \n--Message automatically generated by Balrog wq scripts." %(sys.argv[2]) )
    msg['Subject'] = '%s completed' %(sys.argv[2])
    msg['From'] = sender
    msg['To'] = sender
    
    obj = smtplib.SMTP('localhost')
    obj.sendmail(sender, receivers, msg.as_string())
